### ISSUE TITLE
What is the best Topic to CRUD program

### ISSUE THREAD

**Issue by ad7051** [ad7051/HD_2020OSS_Lab13#2]
We should have to make the CRUD  Program.

**Comment by ad7051** [comment]
What about "user management program" it include Create new user, delete, update and  Read. also we Can add some additional function like login and log out

**Comment by yeon-kyu-0606** [comment]
편의점 같은 곳의 재고를 관리하는 프로그램을 만드는 것도 괜찮을 것 같아

**Comment by ad7051** [comment]
아니면, 가지고 있는 교재들의 리스트를 관리하는 프로그램은 어떨까?

**Comment by ad7051** [comment]
편의점의 재고 관리도 확실히 CRUD 의 용도에 잘맞을 거 같아

**Comment by yeon-kyu-0606** [comment]
그러면 편의점 재고 관리로 미니 프로잭트 만들도록 하자

**Comment by ad7051** [comment]
그러면, 편의점 재고 관리로 결정!
