### ISSUE TITLE
어떤 function들이 "재고관리"프로그램을 만드는데 필요할까? 구조체는 어떤 구조체일까?

### ISSUE THREAD

**Issue by ad7051** [ad7051/HD_2020OSS_Lab13#3]

**Comment by yeon-kyu-0606** [comment]
구조체에는 제품의 이름 ,갯수, 가격 이외에 또 뭐가 들어가야 좋을까?

**Comment by ad7051** [comment]
제품의 종류와 보관방법은 어떨까? 식품인지, 생필품인지, 제품이 냉장인지 냉동인지 상온보관인지

**Comment by yeon-kyu-0606** [comment]
오 제품의 카테고리를 분류하는 거 엄청 괜찮은 것 같애

**Comment by yeon-kyu-0606** [comment]
function에는 제품 만들기, 제품 삭제하기, 갯수 줄이기, 갯수 늘리기, 검색 기능 등을 넣으면 될 것 같애

**Comment by ad7051** [comment]
CRUD 기본에다가 Update에서 추가적으로 갯수 줄이기 늘리기 함수가 더 있다고 생각하면 될까?

**Comment by yeon-kyu-0606** [comment]
좀 애매해지네 그게....

**Comment by yeon-kyu-0606** [comment]
아니면 판매 기능도 포함시켜서 매출을 관리해도 괜찮을 것 같아

**Comment by ad7051** [comment]
그러면CRUD에 재고 UPDATE함수와 검색, 저장, 불러오기에 추가로  판매를  넣고  나는  개인적으로는 폐기 기능도  같이  넣으면  좋을것같아

**Comment by ad7051** [comment]
그런데  폐기의 경우에는  식품들의  유통기한  날짜와 프로그램상  날짜가  존재해야하는데 구조체에 폐기 날짜를  추가 시키고 프로그램 시작시 날짜와  시간을  입력하게 하면  어떨까?

**Comment by yeon-kyu-0606** [comment]
그런데 유통기한을 저장하는 게 좀 힘든 부분일 것 같긴 해 파일 입출력을 통해 관리한다면 같은 이름의 제품 중 유통기한이 다른 제품까지 분류해서 관리하려면 복잡해질 것 같긴 한데...

**Comment by ad7051** [comment]
또  정렬기능으로  가격순  혹은 이름순  정렬도  우선은  생각해봤어

**Comment by ad7051** [comment]
맞네  같은  이름인데  유통기한이  다른  경우도  많구나

**Comment by yeon-kyu-0606** [comment]
오 정렬 기능 되게 좋은 것 같애

**Comment by yeon-kyu-0606** [comment]
카테고리 별 정렬도 되게 괜찮을 것 같다

**Comment by ad7051** [comment]
음 유통기한의 경우에는 차라리 재고를 유통기한 별 재고 이 재고 구조체 는 날짜와 수량으로 이루어져 있고 이 구조채의 배열을 본래의 구조채에서 가지고 있어서, 본래 구조채의 재고 량은 이 하위 구조채 재고 량의 합인걸로

**Comment by ad7051** [comment]
그런데 이렇게 하면 다른 함수들에서 판매같은 함수에서 어렵겠다.

**Comment by yeon-kyu-0606** [comment]
아니면 linked list를 쓰면 유통기한까지 관리할 수 있을 것 같긴 한데...

**Comment by ad7051** [comment]
1.상품 추가
2.상품 출력
3.상품 정보 수정(Update)
4.상품 삭제
5.특정 제품의 재고관리 (Update 재고 관리)
6.판매(재고의 감소 소득 기록)
7.상품 목록 정렬
8.상품  검색
9....

**Comment by yeon-kyu-0606** [comment]
아냐 linked list 써도 엄청 복잡하겠다

**Comment by ad7051** [comment]
그렇지 뭔가 생각보다 복잡하네

**Comment by yeon-kyu-0606** [comment]
상품 검색 쪽에서는 여러가지 function이 나올 수 있을 것 같은데 예를 들면 이름으로 검색, 갯수로 검색 이렇게

**Comment by ad7051** [comment]
현제까지 구조체
1.이름
2. 가격
3.재고 량
4.제품 의 종류

**Comment by ad7051** [comment]
오 그렇네
그러면 그렇게 검색 부분을 분화시켜서 만들면 될것 같다

**Comment by ad7051** [comment]
1.상품 추가
2.상품 출력(전체 출력과 요청 받은 줄만 출력하는함수)
3.상품 정보 수정(Update)
4.상품 삭제
5.특정 제품의 재고관리 (Update 재고 관리)
6.판매(재고의 감소 소득 기록)
7.상품 목록 정렬
 + 정렬 기능세분화 함수들
8.상품 검색 
 +이하의 검색 기능 세분화

**Comment by yeon-kyu-0606** [comment]
이 정도가 딱 괜찮을 것 같애

**Comment by ad7051** [comment]
혹시 구조체에 더  추가할 내용이 있을까?
아, 구조체 말고 메인 함수에 판매 수익 변수가 있어야 겠네

**Comment by ad7051** [comment]
이제 더이상 추가할 내용이 일단은 없는것 같으니 닫고 만약 더 필요해진다면 그때 새롭게 issue를 열도록 할게
