### ISSUE TITLE
역할 분배

### ISSUE THREAD

**Issue by ad7051** [ad7051/HD_2020OSS_Lab13#4]
1.main 함수
2. 기능 함수들(이를 세분화)

함수
1.상품 추가
2.상품 출력(전체 출력과 요청 받은 줄만 출력하는함수)
3.상품 정보 수정(Update)
4.상품 삭제
5.특정 제품의 재고관리 (Update 재고 관리)
6.판매(재고의 감소 소득 기록)
7.상품 목록 정렬
 +정렬 기능세분화 함수들
8.상품 검색
 +이하의 검색 기능 세분화

**Comment by ad7051** [comment]
우선 나는 1~5까지 나누고 6~8부분 나눠서 만들면 될것 같은데
너는 생각이 어때?

**Comment by ad7051** [comment]
1에서 5까지 6에서 8까지

**Comment by yeon-kyu-0606** [comment]
좋아 내 생각에는 2 7 8을 묶는게 편할 것 같아 연관된 function들이니까

**Comment by ad7051** [comment]
오 그래 그게 더 좋겠다. 그러면 그렇게 하자 그러면 2,7,8,을 묶어서 display나 show라는 이름으로 만들고 나머지는 manage라는 이름의 헤더파일로 만들기로 하자

**Comment by yeon-kyu-0606** [comment]
그럼 manage랑 show 중에 어떤 거 할래?? 나는 둘 다 괜찮을 것 같아

**Comment by ad7051** [comment]
그러고 보니 불러오기와 저장을 깜빡했네. 이 두개의 기능도 있네 이 두개도 manage에 넣어서 나는 manage를 할레 이쪽은 이전에 하던 함수들의 간단한 변형이니 양이 많아도 금방 할 수 있을 것 같아.  너는 show를 해도 괜찮아?

**Comment by yeon-kyu-0606** [comment]
오케잉!! 일단 해보면서 서로 어려우면 물어보자

**Comment by ad7051** [comment]
그럼 이걸로 결정! 이것도 닫을게
